version: '3'

# Define services
services:

  frontend:
    restart: always
    build: ./front
    volumes:
      - '.:/usr/src/app'
    expose:
      - "8000"
    depends_on:
      - goapp
    environment:
      - NODE_ENV=development


  # reverse proxy container (nginx)
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - frontend:frontend
    depends_on:
      - frontend


  # go Service
  goapp:
    # Configuration for building the docker image for the service
    build: ./api
    expose:
      - "8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on: 
      - gccapp # This service depends on redis. Start that first.
    environment: # Pass environment variables to the service
      GCC_URL: gccapp:8080   

  # gcc Service   
  gccapp:
    build: ./server
    expose:
      - "9999"
    restart: unless-stopped

